class Alien 
{
    - texture
    - sprite
    - velocidad
    - position
    + Alien()
    + ~Alien()
    + move()
    + draw()
    + update()
    + setPosition()
    + getPosition()
}

class Asteroide
{
    - texture
    - sprite
    - velocidad
    - position
    + Asteroide()
    + ~Asteroide()
    + move()
    + draw()
    + update()
    + setPosition()
    + getPosition()
}

class Enemigo
{
    - texture
    - sprite
    - velocidad
    - position
    + Enemigo()
    + ~Enemigo()
    + move()
    + draw()
    + update()
    + setPosition()
    + getPosition()
}

class Imagen
{
    - texture
    - sprite
    + Imagen()
    + ~Imagen()
    + move()
    + draw()
    + update()
    + setPosition()
    + getPosition()
}

class Personaje
{
    - texture
    - sprite
    - velocidad
    - position
    + Personaje()
    + ~Personaje()
    + move()
    + draw()
    + update()
    + setPosition()
    + getPosition()
}

class Juego
{

}

class Bala
{
    - texture
    - sprite
    - velocidad
    - position
    - disparo
    + Bala()
    + ~Bala()
    + move()
    + draw()
    + update()
    + setPosition()
    + getPosition()
}

class Vida
{
    - texture
    - sprite
    + Vida()
    + ~Vida()
    + move()
    + draw()
    + update()
    + setPosition()
    + getPosition()
}

Juego "1" *-- "1" Personaje
Juego "1" *-- "*" Enemigo
Asteroide --|> Enemigo
Alien --|> Enemigo
Vida --|> Imagen
Personaje "1" o-- "20" Bala
Personaje "1" *-- "3" Vida