
class Juego 
{

}

interface Actualizable
{
    + Actualizar()
}

class Alien 
{
    + Alien()
    + Alien(int x, int y)
    + Actualizar()
    + DesplazarIzquierda()
    + DesplazarDerecha()
    + DesplazarArriba()
    + DesplazarAbajo()
    + Disparar()
    + Morir()
    + ~Alien()

}

class Asteroide
{
    + Asteroide()
    + Asteroide(x, y, recurso)
    + Actualizar()
    + DesplazarIzquierda()
    + DesplazarDerecha()
    + DesplazarArriba()
    + DesplazarAbajo()
    + DesplazarDiagonal()
    + Disparar()
    + Dividir()
    + Morir()
    + ~Asteroide()
}

class Bala 
{
    + Bala(x, y)
    + DesplazarIzquierda()
    + DesplazarDerecha()
    + DesplazarArriba()
    + DesplazarAbajo()
    + Actualizar()
    + ~Bala()
}

class Dibujo
{
    - x
    - y

    + Dibujo()
    + Dibujo(x,y,recurso)
    + Dibujo (recurso)
    + Dibujar()
    + ~Dibujo()
}

class Nave
{
    + Nave()
    + Nave(x,y)
    + Actualizar()
    + DesplazarIzquierda()
    + DesplazarDerecha()
    + DesplazarArriba()
    + DesplazarAbajo()
    + Disparar()
    + Morir()
    + ~Nave()
}

class ObjetoMovil 
{
    + ObjetoMovil()
    + ObjetoMovil(x, y, recurso)
    + DesplazarIzquierda()
    + DesplazarDerecha()
    + DesplazarArriba()
    + DesplazarAbajo()
    + DesplazarDiagonal()
    + Actualizar()
    + ~ObjetoMovil()
}

class Portada 
{
    + Portada()
    + Portada(x, y)
    + Actualizar()
    + ~Portada()
}

class Ventana
{
    + Ventana()
    + Actualizar()
    + Dibujar()
    + ~Ventana()
}

class Color
{
    + Color()
    + Colorear()
    + ~Color()
}

class Velocidad
{
    + Velocidad()
    + Aumentar()
    + Disminuir()
    + ~Velocidad()
}

class Contador
{
    - puntos

    + Contador()
    + Contar()
    + Guardar()
    + ~Contador()
}

Juego "1" *-- "2" Portada
Juego "1" *-- "5" Nivel 
Escenario "1" *-- "*" ObjetoMovil 
Nave --|> ObjetoMovil
Alien --|> ObjetoMovil 
Bala --|> ObjetoMovil 
Asteroide --|> ObjetoMovil 
ObjetoMovil --|> Dibujo 
ObjetoMovil "1" o-- "*" Velocidad 
Portada --|> Dibujo 
Nivel --|> Escenario 
Escenario --|> Ventana
Dibujo --|> Actualizable 
Dibujo "1" *-- "2" Color
Nave "1" o-- "*" Bala
Alien "1" o-- "*" Bala 
Nave "1" o-- "1" Contador